import type { Metadata } from "next";
import "./globals.css";
import { Cairo } from "next/font/google";
import { Toaster } from "sonner";
const cairo = Cairo({subsets: ['arabic'], display: 'swap'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={cairo.className}
      >
        {children}
        <Toaster position="top-center" richColors  />
      </body>
    </html>
  );
}
